name: Hardhat Tests

on:
  push:
    branches: [ "main" ]  # or whatever your default branch name is
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Hardhat tests
        run: npx hardhat test
        
      # Optional: Add coverage reporting
      - name: Run coverage
        run: npx hardhat coverage
        continue-on-error: true  # Coverage might fail but we still want the workflow to continue